spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin # 路由规则，自定义，唯一
          uri: lb://short-link-admin/api/short-link/admin/** # 路由目标微服务，lb代表负载均衡
          predicates: # 路由断言，判断请求是否符合规则，符合则路由到目标
            - Path=/api/short-link/admin/** # 以请求路径做判断，以/api/short-link/admin开头则符合
          # 路由过滤器，对请求或响应做特殊处理
          filters: # 它的作用不是为了拦截谁，而是对于进入网关的前端请求，还有微服务处理完以后得到的相应结果做一些加工和处理
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate
